services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # DataFixtures 相关服务配置区域
  Tourze\TrainCertBundle\DataFixtures\:
    resource: '../../DataFixtures/'
    tags: ['doctrine.fixture.orm']

# Test environment configuration
parameters:
  env(MAILER_DSN): 'smtp://localhost:25'