services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\TrainCertBundle\Command\:
    resource: '../../Command/'
  Tourze\TrainCertBundle\Controller\:
    resource: '../../Controller/'
  Tourze\TrainCertBundle\Procedure\:
    resource: '../../Procedure/'
  Tourze\TrainCertBundle\Repository\:
    resource: '../../Repository/'
  Tourze\TrainCertBundle\Service\:
    resource: '../../Service/'
