services:
  _defaults:
    autowire: true
    autoconfigure: true

  Tourze\TrainCertBundle\Command\:
    resource: '../../Command/'
  Tourze\TrainCertBundle\Controller\:
    resource: '../../Controller/'
  Tourze\TrainCertBundle\Procedure\:
    resource: '../../Procedure/'
  Tourze\TrainCertBundle\Repository\:
    resource: '../../Repository/'
  Tourze\TrainCertBundle\Service\:
    resource: '../../Service/'